Add EventType column for v1.2 in /event service.
GeoNet/fdsn pull request #228
Opened 2022-04-04 22:43 UTC by junghao

Regarding to https://github.com/GeoNet/tickets/issues/10574.
Added `EventType` column for compliance with FDSN event service v1.2.

2022-04-07 04:03 UTC, CallumNZ approved these changes

2022-04-10 21:38 UTC, CallumNZ reviewed
one typo

2022-04-10 21:38 UTC, CallumNZ commented on cmd/fdsn-ws/fdsn_event.go
> +		return e, errors.New("ilimit is not supported.")
limit

2022-04-12 04:18 UTC, CallumNZ approved these changes

2022-04-22 02:41 UTC, CallumNZ requested changes

2022-04-22 02:41 UTC, CallumNZ commented on cmd/fdsn-ws/fdsn_event.go
> +const EVENT_TYPES = `not existing, not reported, earthquake, anthropogenic event, collapse, cavity collapse, mine collapse, building collapse, explosion, accidental explosion, chemical explosion, con
Can this be made multiple lines?

2022-04-22 02:41 UTC, CallumNZ commented on cmd/fdsn-ws/fdsn_event.go
> +		}
Suggestion:

```
if qp == "" {
    err = fmt.Errorf("invalid value for eventtype: %s", e.EventType)
    return e, err
}
e.eventTypeStr = strings.TrimSuffix(qp, ",") // remove the unnecessary last comma
```

2022-04-22 02:41 UTC, CallumNZ commented on cmd/fdsn-ws/routes.go
> +		case http.StatusNoContent, http.StatusNotFound: // NOTE: thought NoContent is not an error but we handled here
*though ?

2022-04-22 03:30 UTC, CallumNZ approved these changes

2022-05-11 04:16 UTC, CallumNZ approved these changes
Looks good.

2023-02-08 19:59 UTC, CallumNZ approved these changes

2023-02-13 03:05 UTC, junghao commented
@CallumNZ I've made an update regarding https://github.com/GeoNet/tickets/issues/12424#issuecomment-1427234143, could you please review? Thanks

2023-02-13 03:10 UTC, CallumNZ approved these changes
Looks good

2023-02-20 04:05 UTC, merged